# Generated by Django 5.1.2 on 2024-10-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=30)),
                ('opening_time', models.CharField(max_length=30)),
            ],
        ),
    ]
